//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalValveToolbox.Properties.translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuNavbar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuNavbar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalValveToolbox.Properties.translations.MenuNavbar", typeof(MenuNavbar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons: .
        /// </summary>
        internal static string menuStrAddons {
            get {
                return ResourceManager.GetString("menuStrAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines: .
        /// </summary>
        internal static string menuStrEngines {
            get {
                return ResourceManager.GetString("menuStrEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login: .
        /// </summary>
        internal static string menuStrLogin {
            get {
                return ResourceManager.GetString("menuStrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string menuStrNone {
            get {
                return ResourceManager.GetString("menuStrNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offilne.
        /// </summary>
        internal static string menuStrOffline {
            get {
                return ResourceManager.GetString("menuStrOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        internal static string menuStrOnline {
            get {
                return ResourceManager.GetString("menuStrOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects: .
        /// </summary>
        internal static string menuStrProjects {
            get {
                return ResourceManager.GetString("menuStrProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam: .
        /// </summary>
        internal static string menuStrSteam {
            get {
                return ResourceManager.GetString("menuStrSteam", resourceCulture);
            }
        }
    }
}
