//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalValveToolbox.Properties.translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalValveToolbox.Properties.translations.MessageBoxes", typeof(MessageBoxes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string msgInfo {
            get {
                return ResourceManager.GetString("msgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelled..
        /// </summary>
        internal static string msgTextCancelled {
            get {
                return ResourceManager.GetString("msgTextCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of.
        /// </summary>
        internal static string msgTextInstallationOf {
            get {
                return ResourceManager.GetString("msgTextInstallationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found..
        /// </summary>
        internal static string msgTextNotFound {
            get {
                return ResourceManager.GetString("msgTextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not installed. Do you want to install it?.
        /// </summary>
        internal static string msgTextNotInstalledInstall {
            get {
                return ResourceManager.GetString("msgTextNotInstalledInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with app id.
        /// </summary>
        internal static string msgTextWithAppID {
            get {
                return ResourceManager.GetString("msgTextWithAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
    }
}
