name: develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-latest
  
    steps:

    - name: Set the value
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - uses: actions/checkout
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget
     
    - name: Restore NuGet Packages
      run: nuget restore src/UniversalValveToolbox.sln
 
    - name: Build Debug
      run: msbuild src/UniversalValveToolbox.sln /p:Configuration=Debug

    - name: Build Release
      run: msbuild src/UniversalValveToolbox.sln /p:Configuration=Release